api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('', views.api_overview, name='api_overview'),
    path('product_list/', views.ProductList.as_view(), name='product_list'),
    path('product_detail/<int:pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('categories_list/', views.CategoryList.as_view(), name='categories_list'),
    path('categories_detail/<int:pk>/', views.CategoriesDetail.as_view(), name='categories_detail'),
    path('subcategories_list/', views.SubCategoriesList.as_view(), name='subcategories_list'),
    path('subcategories_detail/<int:pk>/', views.SubCategoriesDetail.as_view(), name='subcategories_detail'),
]

shop/urls.py
from django.urls import path


from .views import Index, ProductList

app_name = 'shop'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('<str:gender>/', ProductList.as_view(), name='product_list'),
]

shopex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
]

#  ta funkcja sprawdza czy jestem w trybie debugowania
urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path

app_name = 'users'
urlpatterns = [

]

api/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models


# class ProductImage(models.Model):
#     """Image of products."""
#     name = models.CharField(max_length=128, required=True, unique=True)
#     image = models.ImageField()
#     date_added = models.DateTimeField(auto_now_add=True)


class Categories(models.Model):
    """Product category."""
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Subcategories(models.Model):
    """Subcategory of categories, for example winter shoes for shoes."""
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    """Base model for products."""
    CHILD = 'CH'
    MALE = 'MA'
    FEMALE = 'FE'
    UNISEX = 'UN'
    GENDER_CHOICES = [
        (CHILD, 'Child'),
        (MALE, 'male'),
        (FEMALE, 'female'),
        (UNISEX, 'unisex'),
    ]
    title = models.CharField(max_length=128)
    price = models.FloatField(max_length=64)
    category = models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True, blank=True)
    subcategory = models.ForeignKey(Subcategories, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.CharField(max_length=1024, blank=True)
    special_offer = models.BooleanField(default=False)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, blank=True)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ProductsSizes(models.Model):
    """Class connect Product with sizes and contain staff amount."""
    size = models.CharField(max_length=64)
    product = models.ManyToManyField(Product)
    amount = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.product.first().title} | size: {self.size} | amount: {self.amount}"

users/models.py
from django.db import models
from django.contrib.auth.models import User

from shopex.settings import STATIC_URL


def upload_profile_image_path(instance, filename):
    return f'user_{instance.user.id}/profile_images/{filename}'


class ProfileImage(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    upload = models.ImageField(upload_to=upload_profile_image_path)
    upload_at = models.DateTimeField(auto_now_add=True)

api/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, get_list_or_404

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
from rest_framework import generics

from shop.models import Product, Categories, Subcategories
from shop.serializers import ProductSerializer, CategoriesSerializer, SubCategoriesSerializer


# function Product api_view(for learning)
@api_view(['GET'])
def api_overview(request):
    api_urls = {
        "Product List": "/product_list/",
        "Product detail": "/product_detail/<str:pk>/",
        "Categories list": "/categories_list/",
        "Categories detail": "/categories_detail/<str:pk>/",
        "Subcategories list": "/subcategories_list/",
        "Subcategories detail": "/subcategories_detail/<str:pk>/",
    }
    return Response(api_urls)


# @api_view(['GET'])
# def product_list(request):
#     products = get_list_or_404(Product)
#     serializer = ProductSerializer(products, many=True)
#     return Response(serializer.data)
#
#
# @api_view(['GET', 'PUT', 'DELETE'])
# def product_detail(request, pk):
#
#     try:
#         product = get_object_or_404(Product, id=pk)
#     except Product.DoesNotExist:
#         return Response(status=status.HTTP_404_NOT_FOUND)
#
#     if request.method == "GET":
#         serializer = ProductSerializer(product, many=False)
#         return Response(serializer.data)
#     elif request.method == "PUT":
#         serializer = ProductSerializer(product, data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data)
#         else:
#             return Response(serializer.errors, status.HTTP_400_BAD_REQUEST)
#     elif request.method == "DELETE":
#         product.delete()
#         return Response(status=status.HTTP_204_NO_CONTENT)
#
#
# @api_view(['POST'])
# def create_product(request):
#     serializer = ProductSerializer(data=request.data)
#     if serializer.is_valid():
#         serializer.save()
#
#     return Response(serializer.data)


class CategoryList(APIView):

    def get(self, request):
        category = Categories.objects.all()
        serializer = CategoriesSerializer(category, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = CategoriesSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status.HTTP_400_BAD_REQUEST)


class CategoriesDetail(APIView):

    def get(self, request, pk):
        category = get_object_or_404(Categories, id=pk)
        serializer = CategoriesSerializer(category, many=False)
        return Response(serializer.data, status.HTTP_200_OK)

    def put(self, request, pk):
        category = get_object_or_404(Categories, id=pk)
        serializer = CategoriesSerializer(instance=category, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status.HTTP_201_CREATED)
        return Response(serializer.errors, status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        category = get_object_or_404(Categories, id=pk)
        category.delete()
        return Response(status.HTTP_204_NO_CONTENT)


class SubCategoriesList(generics.ListCreateAPIView):
    queryset = Subcategories.objects.all()
    serializer_class = SubCategoriesSerializer


class SubCategoriesDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Subcategories.objects.all()
    serializer_class = SubCategoriesSerializer


class ProductList(generics.ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class ProductDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

shop/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views import View

from .models import Product


class Index(TemplateView):
    template_name = 'shop/index.html'


class ProductList(View):

    def get(self, request, gender):
        products = Product.objects.filter(gender=gender)
        context = {'products': products, 'gender': gender}
        return render(request, 'shop/product_list.html', context)

shop/templates/shop/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Shopex</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% block head %}{% endblock head %}

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="{% url 'shop:index' %}">Shopex</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

        <div class="navbar collapse navbar-collapse" id="navbarCollapse">
            <ul class="mx-auto navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Nowości</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:product_list' 'MA' %}">Mężczyźni</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:product_list' 'FE' %}">Kobiety</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:product_list' 'CH' %}">Dzieci</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Wyprzedaż</a>
                </li>
            </ul>
            <!--
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Witaj, username</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#%}?next=/">Wyloguj</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Zarejestruj się</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Zaloguj</a>
                    </li>
                {% endif %}
            </ul>
            -->
        </div>
    </nav>

{% block content %}
{% endblock content %}

</body>
</html>

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% block content %}

    <p>Strona glowna</p>

    {% if user.is_authenticated %}
        <p>zalogowany</p>
    {% else %}
        <p>nie zalogowany</p>
    {% endif %}
{% endblock content %}

shop/templates/shop/product_list.html
{% extends 'shop/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    <section class="jumbotron text-center">
        <div class="container">
            <h3 style="text-transform: uppercase">{{ products.0.get_gender_display }}</h3>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
          {% if products %}
                {% for product in products %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src={% static 'images/default/default_shoe.png' %} alt="shoe">
                            <div class="card-body">
                                <p class="card-text">Nazwa: {{ product.title }}</p>
                                <p class="card-text">Cena: {{ product.price }} zł</p>
                                <p class="card-text">Marka: {{ product.brand }}</p>
                               <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                  <button type="button" class="btn btn-sm btn-outline-secondary">40</button>
                                  <button type="button" class="btn btn-sm btn-outline-secondary">41</button>
                                  <button type="button" class="btn btn-sm btn-outline-secondary">42</button>
                                  <button type="button" class="btn btn-sm btn-outline-secondary">43</button>
                                  <button type="button" class="btn btn-sm btn-outline-secondary">44</button>
                                  <button type="button" class="btn btn-sm btn-outline-secondary">45</button>
                                </div>
                              </div>
                            </div>
                        </div>
                </div>
            {% endfor %}
        </div>

    {% else %}
        <div>
            <p>Nie ma obecnie dostępnych produktów.</p>
        </div>
    {% endif %}
        </div>
    </div>

{% endblock %}